version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: skailama-backend
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://root:password@mongodb:27017/skailama?authSource=admin
      - JWT_SECRET=your_jwt_secret
      - PORT=5000
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: skailama-frontend
    restart: always
    ports:
      - 5173:5173
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:5000
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mongodb_data: